language: node_js
node_js:
  - '12'

services:
  - docker

before_install:
  - npm i @microservices/cli

script:
  - npx oms build
  - |
    output="$(npx oms run --silent correct -a text='hello foo' | jq -c .)"
    if [ "$output" != '{"results":{"alerts":[],"result":{"sid":1,"rev":0,"score":100,"generalScore":-1,"removed":[],"dialect":"british","foreign":false,"action":"finished"},"original":"hello foo"}}' ] ; then echo "$output"; exit 1; fi
