language: node_js
node_js:
  - "11"

services:
  - docker

before_install:
  - npm i @microservices/cli

script:
  - npx oms build
  - |
    output="$(npx oms run --silent message -a name="Peter" | jq -c .)"
    if [ "$output" != '{"message":"Hello Peter"}' ] ; then echo "$output"; exit 1; fi
